In [1]:
import numpy as np
import pandas as pd
import sklearn
import warnings

In [2]:
datos = pd.read_csv('./loan_data.csv')

datos.columns = ['person_age', 'person_gender', 'person_education', 'person_income', 'person_emp_exp', 'person_home_ownership', 
                 'loan_amnt', 'loan_intent', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score',
                 'previous_loan_defaults_on_file', 'loan_status']

In [3]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object 
 2   person_education                45000 non-null  object 
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64  
 5   person_home_ownership           45000 non-null  object 
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object 
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64  
 12  previous_loan_defaults_on_file  

In [7]:
# Variables categóricas 

datos.select_dtypes(include=['object']).describe()

person_gender person_education person_home_ownership loan_intent  \
count          45000            45000                 45000       45000   
unique             2                5                     4           6   
top             male         Bachelor                  RENT   EDUCATION   
freq           24841            13399                 23443        9153   

       previous_loan_defaults_on_file  
count                           45000  
unique                              2  
top                               Yes  
freq                            22858

In [10]:
# Variables cuantitativas int64

datos.select_dtypes(include=['int64']).describe()

person_emp_exp  credit_score   loan_status
count    45000.000000  45000.000000  45000.000000
mean         5.410333    632.608756      0.222222
std          6.063532     50.435865      0.415744
min          0.000000    390.000000      0.000000
25%          1.000000    601.000000      0.000000
50%          4.000000    640.000000      0.000000
75%          8.000000    670.000000      0.000000
max        125.000000    850.000000      1.000000

In [11]:
# Variables cuantitativas float64

datos.select_dtypes(include=['float64']).describe()

person_age  person_income     loan_amnt  loan_int_rate  \
count  45000.000000   4.500000e+04  45000.000000   45000.000000   
mean      27.764178   8.031905e+04   9583.157556      11.006606   
std        6.045108   8.042250e+04   6314.886691       2.978808   
min       20.000000   8.000000e+03    500.000000       5.420000   
25%       24.000000   4.720400e+04   5000.000000       8.590000   
50%       26.000000   6.704800e+04   8000.000000      11.010000   
75%       30.000000   9.578925e+04  12237.250000      12.990000   
max      144.000000   7.200766e+06  35000.000000      20.000000   

       loan_percent_income  cb_person_cred_hist_length  
count         45000.000000                45000.000000  
mean              0.139725                    5.867489  
std               0.087212                    3.879702  
min               0.000000                    2.000000  
25%               0.070000                    3.000000  
50%               0.120000                    4.000000  
75%               0.190000                    8.000000  
max               0.660000                   30.000000

In [12]:
from sklearn.model_selection import train_test_split
N = len(datos)
cTrain = int(N*0.8)
cTest = N - cTrain
print(N,cTrain,cTest)
train_data, test_data = sklearn.model_selection.train_test_split(datos, train_size=cTrain, test_size=cTest)

45000 36000 9000


In [13]:
train_data.shape

(36000, 14)

In [14]:
train_data.head()

person_age person_gender person_education  person_income  \
6833         23.0          male        Associate        83922.0   
5837         23.0          male        Associate        41783.0   
44408        25.0          male        Associate        53788.0   
18017        28.0        female           Master       241208.0   
26877        27.0        female      High School       140273.0   

       person_emp_exp person_home_ownership  loan_amnt        loan_intent  \
6833                2                  RENT     6000.0            MEDICAL   
5837                2                  RENT     5500.0  DEBTCONSOLIDATION   
44408               1                  RENT    23982.0  DEBTCONSOLIDATION   
18017               5                  RENT    25000.0            VENTURE   
26877               6                   OWN     6000.0            MEDICAL   

       loan_int_rate  loan_percent_income  cb_person_cred_hist_length  \
6833            7.88                 0.07                         2.0   
5837           11.01                 0.13                         3.0   
44408          10.43                 0.45                         4.0   
18017          15.33                 0.10                         7.0   
26877           7.29                 0.04                         7.0   

       credit_score previous_loan_defaults_on_file  loan_status  
6833            624                            Yes            0  
5837            594                            Yes            0  
44408           588                             No            1  
18017           653                            Yes            0  
26877           547                            Yes            0

**Pipeline para atributos categóricos**

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

cat_attribs = ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'previous_loan_defaults_on_file']

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("cat_encoder", OneHotEncoder(sparse_output=False)) #me recomienda usar sparse_output en vez de sparce porque fue renombrado a este
])

**Pipeline para atributos numéricos**

In [31]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

num_attribs = ['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 
               'cb_person_cred_hist_length', 'credit_score']

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy='median')),
    ("scaler", StandardScaler()) # puede ser MinMaxScaler()
])

**Pipeline completo**

In [32]:
from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", cat_pipeline, cat_attribs),
])

In [33]:
X_train = full_pipeline.fit_transform(train_data)

In [34]:
X_train.shape

(36000, 27)

In [35]:
X_train[0,:]

array([-0.78385477,  0.04254   , -0.55794504, -0.56716856, -1.04783058,
       -0.8005294 , -0.99558595, -0.17155156,  0.        ,  1.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  1.        ])

In [36]:
y_train = train_data['loan_status']
y_train

6833     0
5837     0
44408    1
18017    0
26877    0
        ..
40220    0
2405     0
41542    0
23513    1
34980    0
Name: loan_status, Length: 36000, dtype: int64

**Entrenamiento de las redes neuronales** \
Se construyen 5 modelos variando en la topología de la red, la cantidad de capas ocultas y neuronas por capa oculta.

In [37]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

**RED 1**

In [38]:
modelo1 = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(10,5), random_state=123)
modelo1.fit(X_train, y_train)
scores1 = cross_val_score(modelo1, X_train, y_train, cv=5, scoring='neg_mean_absolute_error')
print(scores1)
scores1.mean()

/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS R

[-0.07708333 -0.07777778 -0.08569444 -0.07569444 -0.07888889]


/opt/conda/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


-0.07902777777777778

In [72]:
X_test=full_pipeline.transform(test_data)
X_test

array([[-0.61879989,  0.08338662, -0.72238104, ...,  1.        ,
         0.        ,  1.        ],
       [-0.28869014, -0.59645925, -0.06463705, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.86669397, -0.25824072,  0.59310694, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.0414196 ,  0.47021629, -0.22907305, ...,  0.        ,
         1.        ,  0.        ],
       [-0.61879989, -0.0874093 , -0.39350904, ...,  0.        ,
         0.        ,  1.        ],
       [-0.28869014,  0.43707502, -0.55794504, ...,  1.        ,
         0.        ,  1.        ]])

**Usando los modelos**

In [49]:
y_pred1=modelo1.predict(X_test)
y_pred1

array([0, 0, 0, ..., 0, 0, 0])

**Metricas**

In [62]:
y_test = test_data['loan_status']
y_test

11177    0
6790     0
21385    0
29158    1
42556    1
        ..
9821     0
36568    0
38732    0
35967    0
34332    0
Name: loan_status, Length: 9000, dtype: int64

In [92]:
from sklearn.metrics import mean_absolute_error, accuracy_score
#mean absolute error
mae1=mean_absolute_error(
    y_true = y_test,
    y_pred = y_pred1
) 


#accuracy
acc1 = accuracy_score(
    y_true = y_test,
    y_pred = y_pred1
)
